/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Trans3D.com;

import java.awt.Color;

/**
 *
 * @author Jesus Alejandro Reyna Chavira 19380510 TECNM Cd.Victoria
 */
public class Info extends javax.swing.JFrame {

    /**
     * Creates new form Info
     */
    int xMouse, yMouse;
    public Info() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelInfo = new javax.swing.JPanel();
        HeaderInfo = new javax.swing.JPanel();
        btnSalir = new javax.swing.JPanel();
        IconSalir = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtAutores = new javax.swing.JLabel();
        TxtAutores = new javax.swing.JLabel();
        TxtAutores1 = new javax.swing.JLabel();
        TxtAutores2 = new javax.swing.JLabel();
        TxtAutores3 = new javax.swing.JLabel();
        TxtAutores4 = new javax.swing.JLabel();
        TxtAutores5 = new javax.swing.JLabel();
        TxtInfoTec = new javax.swing.JLabel();
        TxtInfoFecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelInfo.setBackground(new java.awt.Color(86, 200, 216));
        PanelInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HeaderInfo.setBackground(new java.awt.Color(0, 105, 120));
        HeaderInfo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderInfoMouseDragged(evt);
            }
        });
        HeaderInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                HeaderInfoMouseReleased(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(0, 105, 120));
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setPreferredSize(new java.awt.Dimension(47, 47));

        IconSalir.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        IconSalir.setForeground(new java.awt.Color(255, 255, 255));
        IconSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconSalir.setText("X");
        IconSalir.setBorder(null);
        IconSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IconSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        IconSalir.setPreferredSize(new java.awt.Dimension(47, 47));
        IconSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IconSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IconSalirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnSalirLayout = new javax.swing.GroupLayout(btnSalir);
        btnSalir.setLayout(btnSalirLayout);
        btnSalirLayout.setHorizontalGroup(
            btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSalirLayout.createSequentialGroup()
                .addComponent(IconSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnSalirLayout.setVerticalGroup(
            btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IconSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout HeaderInfoLayout = new javax.swing.GroupLayout(HeaderInfo);
        HeaderInfo.setLayout(HeaderInfoLayout);
        HeaderInfoLayout.setHorizontalGroup(
            HeaderInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderInfoLayout.createSequentialGroup()
                .addGap(0, 291, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        HeaderInfoLayout.setVerticalGroup(
            HeaderInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderInfoLayout.createSequentialGroup()
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        PanelInfo.add(HeaderInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 40));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 16)); // NOI18N
        jLabel1.setText("Transformaciónes 3D en Java3D");
        PanelInfo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Black", 1, 10)); // NOI18N
        jLabel2.setText("v1.0");
        PanelInfo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, 10));

        txtAutores.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        txtAutores.setText("Autores:");
        PanelInfo.add(txtAutores, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        TxtAutores.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        TxtAutores.setText("Obregon Tejada Luis Manuel");
        PanelInfo.add(TxtAutores, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        TxtAutores1.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        TxtAutores1.setText("León Rodea Andrei Uriel");
        PanelInfo.add(TxtAutores1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        TxtAutores2.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        TxtAutores2.setText("Ayala Rivera Ruben");
        PanelInfo.add(TxtAutores2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        TxtAutores3.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        TxtAutores3.setText("Reyna Chavira Jesus Alejandro");
        PanelInfo.add(TxtAutores3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        TxtAutores4.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        TxtAutores4.setText("Cruz Muñoz Victor Alejandro");
        PanelInfo.add(TxtAutores4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        TxtAutores5.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        TxtAutores5.setText("Galaviz Quintanilla Javier Ulises");
        PanelInfo.add(TxtAutores5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        TxtInfoTec.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        TxtInfoTec.setText("Instituto Tecnologico de Cd Victoria");
        PanelInfo.add(TxtInfoTec, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        TxtInfoFecha.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        TxtInfoFecha.setText("Agosto - Diciembre 2022");
        PanelInfo.add(TxtInfoFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, -1, -1));

        getContentPane().add(PanelInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 498));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IconSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconSalirMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_IconSalirMouseClicked

    private void IconSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconSalirMouseEntered
        btnSalir.setBackground(Color.red);
        btnSalir.setForeground(Color.white);
    }//GEN-LAST:event_IconSalirMouseEntered

    private void IconSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconSalirMouseExited
        btnSalir.setBackground(HeaderInfo.getBackground());
        btnSalir.setForeground(Color.black);
    }//GEN-LAST:event_IconSalirMouseExited

    private void HeaderInfoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderInfoMouseReleased
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_HeaderInfoMouseReleased

    private void HeaderInfoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderInfoMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_HeaderInfoMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HeaderInfo;
    public javax.swing.JLabel IconSalir;
    private javax.swing.JPanel PanelInfo;
    private javax.swing.JLabel TxtAutores;
    private javax.swing.JLabel TxtAutores1;
    private javax.swing.JLabel TxtAutores2;
    private javax.swing.JLabel TxtAutores3;
    private javax.swing.JLabel TxtAutores4;
    private javax.swing.JLabel TxtAutores5;
    private javax.swing.JLabel TxtInfoFecha;
    private javax.swing.JLabel TxtInfoTec;
    private javax.swing.JPanel btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel txtAutores;
    // End of variables declaration//GEN-END:variables
}
